"""
Ref: https://leetcode.com/problems/find-the-difference/description/?envType=problem-list-v2&envId=bit-manipulation

You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
----------
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
----------
Input: s = "", t = "y"
Output: "y"
 
Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        num = 0
        s_len = len(s)
        for i in range(len(t)):
            s_num = ord(s[i]) if i < s_len else 0
            num ^= s_num ^ ord(t[i])
        #print(f"num: {num}; ch: {chr(num)}")
        return chr(num)

sol = Solution()

print("TEST 1")
s = "abcd"
t = "abcde"
exp = "e"
result = sol.findTheDifference(s, t)
assert result == exp

print("TEST 2")
s = ""
t = "y"
exp = "y"
result = sol.findTheDifference(s, t)
assert result == exp